セキュリティのリスクがあるため^は\Aに置き換え
下記エラーに対する処置
ArgumentError: The provided regular expression is using multiline anchors (^ or $), which may present a security risk. Did you mean to use \A and \z, or forgot to add the :multiline => true option?